const actionTypes = {
	GET_OVERALL_DATA: 'GET_OVERALL_DATA',
	GET_ALL_COUNTRIES: 'GET_ALL_COUNTRIES',
	GET_ALL_COUNTRIES_DATA: 'GET_ALL_COUNTRIES_DATA',
	UPDATE_SELECTED_COUNTRY: 'UPDATE_SELECTED_COUNTRY',
	UPDATE_COUNTRYWISE_DATA: 'UPDATE_COUNTRYWISE_DATA',
	UPDATE_DRILLED_COUNTRY_DATA: 'UPDATE_DRILLED_COUNTRY_DATA',
	GET_USA_DETAILED_DATA: 'GET_USA_DETAILED_DATA',
	GET_ALL_INDIA_DETAILED_DATA: 'GET_ALL_INDIA_DETAILED_DATA',
	SORT_DATA_BY_REQUEST: 'SORT_DATA_BY_REQUEST',
};

export default actionTypes;
