const actionTypes = {
	GET_DEFAULT_COUNTRY: 'GET_DEFAULT_COUNTRY',
	UPDATE_DEFAULT_COUNTRY: 'UPDATE_DEFAULT_COUNTRY',
	GET_OVERALL_DATA: 'GET_OVERALL_DATA',
	GET_ALL_COUNTRIES: 'GET_ALL_COUNTRIES',
	UPDATE_SELECTED_COUNTRY: 'UPDATE_SELECTED_COUNTRY',
	UPDATE_COUNTRYWISE_DATA: 'UPDATE_COUNTRYWISE_DATA',
	UPDATE_DRILLED_COUNTRY_DATA: 'UPDATE_DRILLED_COUNTRY_DATA',
};

export default actionTypes;
