const strings = {
	en: {
		lastUpdated: 'Last updated ',
		country: 'Country',
		continent: 'Continent',
		population: 'Total population',
		tests: 'Total tests',
		testsPerOneMillion: 'Tests/Million',
		oneTestPerPeople: 'One test per person',
		cases: 'Confirmed Cases',
		casesPerOneMillion: 'Cases/Million',
		todayCases: 'Cases confirmed today',
		oneCasePerPeople: 'One case per person',
		deaths: 'Deaths',
		deathsPerOneMillion: 'Deaths/Million',
		todayDeaths: 'Today deaths',
		oneDeathPerPeople: 'One death per person',
		recovered: 'Recovered',
		recoveredPerOneMillion: 'Recovered/Million',
		todayRecovered: 'Today recovered',
		activeCases: 'Active cases',
		activePerOneMillion: 'Active cases/Million',
		critical: 'Critical cases',
		criticalPerOneMillion: 'Critical cases/Million',
		datasource: 'Data sources - disease.sh,  api.covid19india.org',
		stateOrUT: 'State / UT',
		state: 'State',
		confirmedWithDelta: 'Confirmed(*)',
		active: 'Active',
		recoveredWithDelta: 'Recovered(*)',
		deathsWithDelta: 'Deaths(*)',
		'*': ' - Numbers with arrow signs = Delta from previous count',
	},
};
export default strings;
