export const indiaStateCodeMap = {
	AN: { stateName: 'Andaman and Nicobar Islands' },
	AP: { stateName: 'Andhra Pradesh' },
	AR: { stateName: 'Arunachal Pradesh' },
	AS: { stateName: 'Assam' },
	BR: { stateName: 'Bihar' },
	CH: { stateName: 'Chandigarh' },
	CT: { stateName: 'Chhattisgarh' },
	DL: { stateName: 'Delhi' },
	DN: { stateName: 'Dadra and Nagar Haveli and Daman and Diu' },
	GA: { stateName: 'Goa' },
	GJ: { stateName: 'Gujarat' },
	HP: { stateName: 'Himachal Pradesh' },
	HR: { stateName: 'Haryana' },
	JH: { stateName: 'Jharkhand' },
	JK: { stateName: 'Jammu and Kashmir' },
	KA: { stateName: 'Karnataka' },
	KL: { stateName: 'Kerala' },
	LA: { stateName: 'Ladakh' },
	MH: { stateName: 'Maharashtra' },
	ML: { stateName: 'Meghalaya' },
	MN: { stateName: 'Manipur' },
	MP: { stateName: 'Madhya Pradesh' },
	MZ: { stateName: 'Mizoram' },
	NL: { stateName: 'Nagaland' },
	OR: { stateName: 'Odisha' },
	PB: { stateName: 'Punjab' },
	PY: { stateName: 'Puducherry' },
	RJ: { stateName: 'Rajasthan' },
	SK: { stateName: 'Sikkim' },
	TG: { stateName: 'Telangana' },
	TN: { stateName: 'Tamilnadu' },
	TR: { stateName: 'Tripura' },
	TT: { stateName: 'All India' },
	UP: { stateName: 'Uttar Pradesh' },
	UT: { stateName: 'Uttarakhand' },
	WB: { stateName: 'West Bengal' },
};
